# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calcFijPairwiseCpp <- function(alfreq1, alfreq2, ref_al_freq, n_loci, n_alleles_per_loci, n_gene_copies) {
    .Call('dispersim_calcFijPairwiseCpp', PACKAGE = 'dispersim', alfreq1, alfreq2, ref_al_freq, n_loci, n_alleles_per_loci, n_gene_copies)
}

calcFijPopCpp <- function(gen_data, ref_al_freq, offspr_gen, n_loci, n_alleles_per_loci, n_gene_copies) {
    .Call('dispersim_calcFijPopCpp', PACKAGE = 'dispersim', gen_data, ref_al_freq, offspr_gen, n_loci, n_alleles_per_loci, n_gene_copies)
}

calcAlleleFreqCpp <- function(gen_data, n_loci, n_alleles_per_loci) {
    .Call('dispersim_calcAlleleFreqCpp', PACKAGE = 'dispersim', gen_data, n_loci, n_alleles_per_loci)
}

